#!/bin/sh

# M106: Fan On
# Example: M106 S127
# Turn on the cooling fan at half speed.
# Mandatory parameter 'P' declares the PWM value (0-255).
# M106 P0 turns the fan off. 

halcmd setp hpg.pwmgen.00.out.04.value $1
#halcmd sets fan.speed.set $1

exit 0

